name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

#     - name: Set up Go 1.13
#       uses: actions/setup-go@v1
#       with:
#         go-version: 1.13
#       id: go

    
    - name: update deploy status
      if: always()
      uses: unacast/actions-github-deployment-status@[version]
      with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           status: ${{ job.status }}
           description: "The description to create. Restricted to 140 chars"
      
    - uses: yanzay/notify-telegram@master
      if: always()
      with:
        chat: ${{ secrets.chat }}
        token: ${{ secrets.token }}
        status: ${{ job.status }}
